---
title: "eu-pca-clustering"
author: "Patrycja Kornobis"
date: "`r Sys.Date()`"
output: github_document
---
``` {r setup}
# Załadowanie potrzebnych bibliotek
library(readxl)
library(tidyverse)
library(ggrepel)
library(psych)
library(FactoMineR)
library(dplyr)
library(ggplot2)
library(factoextra)
library(DataExplorer)
library(fpc) 
library(corrplot)
```

```{r}
#============================== P  C  A ========================================


# załadownaie w przekształcenie danych
eu <- read_excel("data/dane.xlsx")
names(eu) <- c( "Kraj" , "Wyższe wyksz.", "Personel w R&D",
                "Specjaliści ICT", "Patenty", "Wydatki na R&D", "Kursy online")

# sprawdzamy na wykresie punktowym czy istnieją wartości odstające
pairs(eu[, -1])
# możemy zauważyć, że jeden kraj odstają od reszty pod względem liczby patentów

# identyfikacja kraju z odstającą ilością patentów
eu %>% 
  ggplot(aes(x = Patenty, 
             y = reorder(Kraj, Patenty), 
             fill = Patenty)) + 
  geom_col() +
  scale_fill_gradient(low = "yellow", high = "red") +
  theme_minimal() +
  labs( y = "Kraj",
        title = "Ilość patentów na mieszkańca - Skala gradientowa", 
        fill = "Ilość patentów")
# teraz możemy zauważyć, że tym krajem jest Szwajcarja

# odrzucamy ten kraj 
eu <- eu %>% filter(!Kraj %in% c("Switzerland") )




# 1. SPRAWDZAMY czy można zrobic pca? ---------------------------------------------

# wykres korelacji
corrplot(cor(eu[, -1]), order = "hclust", tl.cex = 0.7) 

# test bartletta
cortest.bartlett(cor(eu[, -1])) 
# p-value < 0,05 

# KMO kryterium
KMO(cor(eu[, -1])) 
# Overall MSA =  0.68

# na podstawie powyższych kryteriów stwierdzamy, że można wykonać pca


# 2. wybór LICZBY SKŁADOWYCH ---------------------------------------------------

# najpierw przeprowadzamy PCA dla 6 składowych, 
# aby wybrać ostateczną liczbe nowych wymiarów
pr.eu0 <- principal( eu[, -1], nfactors = 6, rotate = "none")
pr.eu0$loadings

# pierwsza skladowa wyjasnia 62%, druga 19% zmiennościu zbioru danych
# w sumie pierwsze 2 wyjasniaja ok. 80% zmiennosci, co jest dobrym wynikiem


# wykres osypiska
fviz_screeplot( PCA(eu[, -1],graph = FALSE ), barfill = "lightblue", 
                addlabels = TRUE, choice = "eigenvalue") +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red")
# dwie skladowe powyzej 1 (kryterium Kaisera)

# WNIOSEK: wybieramy 2 składowe


# 3. ANALIZA i INTERPRETACJA składowych ----------------------------------------

pr.eu <- principal( eu[, -1], nfactors = 2, rotate = "none")
pr.eu

old.par <- par() 
biplot(pr.eu)
par(old.par)

# wykonujemy dodatkową rotacje dla łatwiejszej interpretacji składowych 
pr.eu <- principal( eu[, -1], nfactors = 2, rotate = "varimax")
pr.eu$loadings

old.par <- par() 
biplot(pr.eu, col = c("darkgrey", "#1E90FF"), pch = 16)
par(old.par)


# Interpretacja nowych składowych
# RC1 - Poziom zaangażowania kraju w badania i rozwój
#       wysokie wydatki na R&D > wiecej presonelu > więcej zgłoszeń patentowych
# RC2 - Poziom wykształcenia i wiedzy społeczeństwa
#       to co ludzie potrafią i jak się rozwijają (samokształcenie, studia)
#       jakość wiedzy, specjaliści > wysoka wiedza technologiczna 


# 4. wykres z nowymi składowymi ------------------------------------------------

# ramaka danych z wartościami nowych składowych 
eu.RC <- pr.eu$scores %>% as.data.frame()
names(eu.RC) <- c("Poziom zaangażowania kraju w badania i rozwój",
                  "Poziom wykształcenia i wiedzy społeczeństwa")
eu.RC$Kraj <- eu$Kraj


# Rozmieszczenie krajów w przestrzeni nowych składowych
eu.RC %>% 
  ggplot( aes( x=`Poziom zaangażowania kraju w badania i rozwój`,
               y = `Poziom wykształcenia i wiedzy społeczeństwa`))+
  geom_point()+
  geom_text(aes(label = Kraj), vjust = -1, size = 3)+
  theme_light()+
  labs(title = "Rozmieszczenie krajów w przestrzeni nowych składowych")







#============================= ANALIZA SKUPIEŃ =================================




# SPRAWDZENIE danych, rozkladow ------------------------------------------------

# ponowne sprawdzenie danych
pairs(eu[, -1])
# przez wcześniejsze odrzucenie odstającego kraju teraz wszystko jest w porządku


# STANDARYZACJA ----------------------------------------------------------------
eu.scaled <- scale(eu[, -1]) %>% as.data.frame()
summary(eu.scaled) # sprawdzamy dane, wszystkie średnie równe 0



# grupowanie HIERARCHICZNE -----------------------------------------------------

d <- dist(eu.scaled, method = "euclidean") # macierz dystnsu 

## grupowanie metodą WARDERA ---------------------------------------------------
hc1 <- hclust(d, method = "ward.D2")       # tworzymy obiekt klasy hclust

# dendogram 
plot(hc1, 
     labels = eu$Kraj, 
     cex = 0.6,
     main = "Analiza skupień krajów europejskich", 
     sub = "",                                    
     xlab = "Kraje",                              
     ylab = "Dystans (Euklidesowy)"               
)
# na dendogramie widać wyraźny podział na 2, 3 grupy 

# sprawdzamy ich liczebność
# podział na 2 grupy 
cutree(hc1, k = 2) %>% table()
# podział na 3 grupy
cutree(hc1, k = 3) %>% table()

# wybieramy podziałna 3 grupy 
plot(hc1, 
     labels = eu$Kraj, 
     cex = 0.6,
     main = "Analiza skupień krajów europejskich", 
     sub = "",                                    
     xlab = "Kraje",                              
     ylab = "Dystans (Euklidesowy)"               
)
rect.hclust(hc1, k = 3, border = c("#F8766D", "#619CFF","#00BA38"))

# stabilność grup 
clusterboot(eu.scaled, B = 500,
            clustermethod = hclustCBI, method = "ward.D2", k = 3)


## CHARAKTERYSTYKA grup ---------------------------------------------------------

# dodajemy nową kolumne do danych z etykietkami grupy
eu$cluster.w <- cutree(hc1, k = 3) %>% factor()


# na podstawie wykresów interpretujemy powstałe grupy
plot_boxplot(eu, 
             by = "cluster.w", 
             ncol = 3, 
             geom_boxplot_args = list("fill" = "#CAE1FF"),
             title = "Porównanie klastrów", 
             ggtheme = theme_bw())







# grupowanie K-MEANS -----------------------------------------------------------

# wybierzmy na poczatek 4 grupy, utworzmy obiekt klasy kmeans, 
# pracujemy na danych ustandaryzowanych 
set.seed(10)
km1 <- kmeans(eu.scaled, centers = 4, nstart = 10)

km1$cluster        # podzial na grupy w elemencie cluster
km1$withinss       # wartosci sumy kwadratow odleglosci w poszczegolnych grupach
km1$tot.withinss   # suma withinss, WSS 



## wybór liczby grup -----------------------------------------------------------


# wykres osypiska WSS
x <- rep(0, 10) 
for(i in 1:10)
  x[i] <- kmeans(eu.scaled, centers = i, nstart = 10)$tot.withinss

# wykres
plot(x, type = "b")
# wniosek: 2 grupy




# kryterium ch (Calinskiego-Harabasza)
km.ch <- kmeansruns(eu.scaled, criterion = "ch", runs = 10)

# wykres
plot(km.ch$crit, type = "b")
# wniosek: 2 grupy 



# kryterium asw (Average Silhouette
km.asw <- kmeansruns(eu.scaled, criterion = "asw", runs = 10)

# wykres
plot(km.asw$crit, type = "b")
# wniosek: 2 lub 4  grupy




# WNIOSEK: wybieramy 2 grupy 
set.seed(10)
km1 <- kmeans(eu.scaled, centers = 2, nstart = 10)


# dokładamy grupowanie do ramki z danymi jako kolejna zmienna
eu$cluster.km <- km1$cluster %>% factor()


## CHARAKTERYSTYKA grup --------------------------------------------------------

# na podstawie wykresów interpretujemy powstałe grupy
plot_boxplot(eu, 
             by = "cluster.km", 
             ncol = 3, 
             geom_boxplot_args = list("fill" = "#CAE1FF"),
             title = "Porównanie klastrów", 
             ggtheme = theme_bw())

#zmieniamy kraje wysoko rozwinięte jako grupa 1
eu$cluster.km <- factor(eu$cluster.km,
                        levels = c(2,1),
                        labels = 1:2)

#sprawdzamy jeszcze raz
plot_boxplot(eu, 
             by = "cluster.km", 
             ncol = 3, 
             geom_boxplot_args = list("fill" = "#CAE1FF"),
             title = "Porównanie klastrów", 
             ggtheme = theme_bw())



# stabilność grupy
clusterboot(eu.scaled, B = 500,
            clustermethod = kmeansCBI, krange = 2)


# PORÓWNANIE GRUPOWAŃ ----------------------------------------------------------

table(eu$cluster.w, eu$cluster.km)





# PCA i grupwanie razem --------------------------------------------------------

# dokładamy etykietki grupowań do ramki danych z wartościami 
# nowych wymiarów
eu.RC$cluster.w <- eu$cluster.w
eu.RC$cluster.km <- eu$cluster.km


# nowe wymiary i grupowanie hierarhiczne wardera
eu.RC %>% 
  ggplot( aes( x=`Poziom zaangażowania kraju w badania i rozwój`,
               y = `Poziom wykształcenia i wiedzy społeczeństwa`))+
  geom_point( aes( color= cluster.w), size = 1.7)+
  geom_text(aes(label = Kraj), vjust = -1, size = 2.5)+
  theme_light()+
  labs(title = "Rozmieszczenie krajów w przestrzeni nowych składowych")

# nowe wymiary i grupowanie kmeans
eu.RC %>% 
  ggplot( aes( x=`Poziom zaangażowania kraju w badania i rozwój`,
               y = `Poziom wykształcenia i wiedzy społeczeństwa`))+
  geom_point( aes( color= cluster.km),size = 1.7)+
  geom_text(aes(label = Kraj), vjust = -1, size = 2.5)+
  theme_light()+
  labs(title = "Rozmieszczenie krajów w przestrzeni nowych składowych")

# nowe wymiary i grupowanie wardera + elipsa
eu.RC %>% 
  ggplot(aes(x = `Poziom zaangażowania kraju w badania i rozwój`, 
             y = `Poziom wykształcenia i wiedzy społeczeństwa`,
             color = factor(cluster.w))) + 
  geom_point() +
  stat_ellipse(aes(fill = factor(cluster.w)), 
               geom = "polygon", 
               alpha = 0.15, 
               level = 0.95) + 
  geom_text(aes(label = Kraj), vjust = -1, size = 2.5) +
  theme_light() +
  labs(title = "Rozmieszczenie krajów w przestrzeni nowych składowych",
       color = "Klaster",
       fill = "Klaster")

# nowe wymiary i grupowanie kmean + elipsa
eu.RC %>% 
  ggplot(aes(x = `Poziom zaangażowania kraju w badania i rozwój`, 
             y = `Poziom wykształcenia i wiedzy społeczeństwa`,
             color = factor(cluster.km))) + 
  geom_point() +
  stat_ellipse(aes(fill = factor(cluster.km)), 
               geom = "polygon", 
               alpha = 0.15, 
               level = 0.95) + 
  geom_text(aes(label = Kraj), vjust = -1, size = 2.5) +
  theme_light() +
  labs(title = "Rozmieszczenie krajów w przestrzeni nowych składowych",
       color = "Klaster",
       fill = "Klaster")

```